
import java.util.Random;
import javax.swing.JOptionPane;


public class jframe extends javax.swing.JFrame {

    /**
     * Creates new form jframe
     */
    public jframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sentMsg = new javax.swing.JTextField();
        buttonwithout = new javax.swing.JButton();
        buttonwith = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        recievedMsg = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        errorchecker = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        correctDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hamming  Code");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Data 4bits only");

        sentMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sentMsgActionPerformed(evt);
            }
        });

        buttonwithout.setText("send without Error");
        buttonwithout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonwithoutActionPerformed(evt);
            }
        });

        buttonwith.setText("send with Error");
        buttonwith.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonwithActionPerformed(evt);
            }
        });

        jLabel3.setText("Recieved Data");

        jLabel5.setText("Error Check !");

        jLabel7.setText("Correct Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(336, 336, 336))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(buttonwithout, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonwith, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sentMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(recievedMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(correctDate, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                        .addGap(158, 158, 158)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(errorchecker, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sentMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonwith, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(buttonwithout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(errorchecker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(recievedMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(correctDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sentMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sentMsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sentMsgActionPerformed

    private void buttonwithoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonwithoutActionPerformed
        // TODO add your handling code here:
        
       int []sentmsg=new int[8];
       int []recieved =new int[8];
        if(sentMsg.getText().length()!=4){
            JOptionPane.showMessageDialog(this, "You should enter 4 bits only");
        }
       char[] msg=sentMsg.getText().toCharArray();
        for(int i=0;i<msg.length;i++){
            if(msg[i]!='1'&&msg[i]!='0'){
               JOptionPane.showMessageDialog(this, "You should enter 1's and 0's only");
               return;
            }
        }
        
        sentmsg[3]=Integer.parseInt(msg[0]+"");
        sentmsg[5]=Integer.parseInt(msg[1]+"");
        sentmsg[6]=Integer.parseInt(msg[2]+"");
        sentmsg[7]=Integer.parseInt(msg[3]+"");
sentmsg[1]=sentmsg[3]^sentmsg[5]^sentmsg[7];
sentmsg[2]=sentmsg[3]^sentmsg[6]^sentmsg[7];
sentmsg[4]=sentmsg[5]^sentmsg[6]^sentmsg[7];
       
for(int i=1;i<sentmsg.length;i++)System.out.print(sentmsg[i]);

//sending data
for(int i=1;i<sentmsg.length;i++)recieved[i]=sentmsg[i];


String str="";
str+=recieved[3];
str+=recieved[5];
str+=recieved[6];
str+=recieved[7];
recievedMsg.setText(str);
int p1,p2,p3;

p1=recieved[1]^recieved[3]^recieved[5]^recieved[7];
p2=recieved[2]^recieved[3]^recieved[6]^recieved[7];
p3=recieved[4]^recieved[5]^recieved[6]^recieved[7];

int sum=p1+p2*2+p3*4;

if(sum==0){
   System.out.println();
       System.out.println("No error");

errorchecker.setText("No error!");


}
        
else{
    System.out.println();
       System.out.println("error");
    
       errorchecker.setText("error!");

       
       
       if(recieved[sum]==1){
           recieved[sum]=0;
       }
       else recieved[sum]=1;
               
   
       
       
       
               }


          
    }//GEN-LAST:event_buttonwithoutActionPerformed

    private void buttonwithActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonwithActionPerformed
         
       int []sentmsg=new int[8];
       int []recieved =new int[8];
        if(sentMsg.getText().length()!=4){
            JOptionPane.showMessageDialog(this, "You should enter 4 bits only");
        }
       char[] msg=sentMsg.getText().toCharArray();
        for(int i=0;i<msg.length;i++){
            if(msg[i]!='1'&&msg[i]!='0'){
               JOptionPane.showMessageDialog(this, "You should enter 1's and 0's only");
               return;
            }
        }
        
        sentmsg[3]=Integer.parseInt(msg[0]+"");
        sentmsg[5]=Integer.parseInt(msg[1]+"");
        sentmsg[6]=Integer.parseInt(msg[2]+"");
        sentmsg[7]=Integer.parseInt(msg[3]+"");
sentmsg[1]=sentmsg[3]^sentmsg[5]^sentmsg[7];
sentmsg[2]=sentmsg[3]^sentmsg[6]^sentmsg[7];
sentmsg[4]=sentmsg[5]^sentmsg[6]^sentmsg[7];
       
for(int i=1;i<sentmsg.length;i++)System.out.print(sentmsg[i]);

//sending data
for(int i=1;i<sentmsg.length;i++)recieved[i]=sentmsg[i];

Random m=new Random();

int x=m.nextInt(7);

while(x==0){
   x=m.nextInt(7); 
}

if(recieved[x]==0)recieved[x]=1;
else recieved[x]=0;

String str="";
str+=recieved[3];
str+=recieved[5];
str+=recieved[6];
str+=recieved[7];




recievedMsg.setText(str);
int p1,p2,p3;

p1=recieved[1]^recieved[3]^recieved[5]^recieved[7];
p2=recieved[2]^recieved[3]^recieved[6]^recieved[7];
p3=recieved[4]^recieved[5]^recieved[6]^recieved[7];

int sum=p1+p2*2+p3*4;

if(sum==0){
   System.out.println();
       System.out.println("No error");

errorchecker.setText("No error!");


}
        
else{
    System.out.println();
       System.out.println("error");
    
       errorchecker.setText("error!");

       
       
       if(recieved[sum]==1){
           recieved[sum]=0;
       }
       else recieved[sum]=1;
               
   String str2="";
str2+=recieved[3];
str2+=recieved[5];
str2+=recieved[6];
str2+=recieved[7];
       
     correctDate.setText(str2);
       
               }
        
        
        
        
        
        
    }//GEN-LAST:event_buttonwithActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonwith;
    private javax.swing.JButton buttonwithout;
    private javax.swing.JLabel correctDate;
    private javax.swing.JLabel errorchecker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel recievedMsg;
    private javax.swing.JTextField sentMsg;
    // End of variables declaration//GEN-END:variables
}
